---
title: "Exploratory Analysis"
author: "Abdullah Hammamy"
date: "2022-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```

```{r}
data1 <- "https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx"
lcl <- basename(data1)
download.file(url = data1, destfile = lcl)
library(readxl)
ENB2012_data <- read_excel(lcl)
library(ggplot2)

ENB2012_data$X2 <- as.factor(ENB2012_data$X2)
ggplot(data=ENB2012_data, aes(x=X2, y=Y1)) + geom_boxplot() + xlab("Surface Area (Lengths^2)") + ylab("Heating Load (BTU)")
ggplot(data=ENB2012_data, aes(x=X2, y=Y2)) + geom_boxplot() + xlab("Surface Area (Lengths^2)") + ylab("Cooling Load (BTU)")

ENB2012_data$X4 <- as.factor(ENB2012_data$X4)
ggplot(data=ENB2012_data, aes(x=X4, y=Y1)) + geom_boxplot() + xlab("Roof Area (Lengths^2)") + ylab("Heating Load (BTU)")
ggplot(data=ENB2012_data, aes(x=X4, y=Y2)) + geom_boxplot() + xlab("Roof Area (Lengths^2)") + ylab("Cooling Load (BTU)")

ENB2012_data$X5 <- as.factor(ENB2012_data$X5)
ggplot(data=ENB2012_data, aes(x=X5, y=Y1)) + geom_boxplot() + xlab("Overall Height (lengths)") + ylab("Heating Load (BTU)")
ggplot(data=ENB2012_data, aes(x=X5, y=Y2)) + geom_boxplot() + xlab("Overall Height (lengths)") + ylab("Cooling Load (BTU)")

ENB2012_data$X7 <- as.factor(ENB2012_data$X7)
ggplot(data=ENB2012_data, aes(x=X7, y=Y1)) + geom_boxplot() + xlab("Glazing Area (Lengths^2)") + ylab("Heating Load (BTU)")
ggplot(data=ENB2012_data, aes(x=X7, y=Y2)) + geom_boxplot() + xlab("Glazing Area (Lengths^2)") + ylab("Cooling Load (BTU)")
```

```{r}
data1 <- "https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx"
lcl <- basename(data1)
download.file(url = data1, destfile = lcl)
library(readxl)
ENB2012_data <- read_excel(lcl)
library(ggplot2)
df <- ENB2012_data %>% rename("Surface Area"=X2, "Roof Area"=X4, "Overall Height"=X5, "Glazing Area"=X7) %>% select(2,4,5,7)
cormat <- df %>% cor()
cormat
cor_table <- cormat %>% as.data.frame %>% rownames_to_column("var1")
tidycor <- cor_table %>% pivot_longer(-1, names_to = "var2", values_to = "correlation")
tidycor %>% ggplot(aes(var1, var2, fill=correlation)) + geom_tile() + scale_fill_gradient2(low="red", mid="white", high = "blue") + geom_text(aes(label=round(correlation,2)),color = "black", size = 4) + theme(axis.text.x = element_text(angle = 90)) + coord_fixed()
```

